ASP/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from airsupply import views

urlpatterns = [

    path('main/', include('airsupply.urls')),
    path('admin/', admin.site.urls, name='admin_page'),


]

airsupply/urls.py
from django.urls import path, re_path
from . import views

app_name = 'airsupply'

urlpatterns = [

    #users
    re_path(r'^$', views.UserLoginView.as_view(), name='login'),
    re_path(r'^logout/$', views.logout_user, name='logout'),
    path('account/', views.UserAccount.as_view(), name='account'),
    re_path(r'^register/(?P<usernameb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.UserRegisterView.as_view(), name='register'),
    re_path(r'^register/$', views.UserRegisterView.as_view(), name='confirm_registration'),
    re_path(r'^forgot_password/$', views.UserForgotPassword.as_view(), name='forgot_password'),

    #clinic manager
    path('browse/', views.BrowseView.as_view(), name='browse'),
    re_path(r'browse/(?P<catID>[0-9]+)/$', views.BrowseView.as_view(), name='browse_cat'),
    path('cart/', views.CartView.as_view(),  name='cart'),
    path('my_orders/', views.OrderView.as_view(), name='my_orders'),
    re_path(r'my_orders/cancel/(?P<pk>[0-9]+)/$', views.cancelOrder, name='cancel_order'),
    re_path(r'my_orders/receive/(?P<pk>[0-9]+)/$', views.receiveOrder, name='receive_order'),
    path('cart/add/', views.cart_add, name='cart_add'),  # Change main.js too if URL is changed
    path('cart/checkout/', views.cart_checkout, name='cart_checkout'),
    re_path(r'order/(?P<pk>[0-9]+)/$', views.OrderDetailView.as_view(), name='view_order_details'),
    re_path(r'remove_item/(?P<order_pk>[0-9]+)/(?P<item_pk>[0-9]+)/$', views.delete_item, name='remove_item'),

    #dispatcher
    path('dispatch/', views.DispatchView.as_view(), name='dispatch_view'),
    re_path(r'dispatch/itinerary/(?P<pk>[0-9]+)/$', views.get_itinerary, name='get_itinerary'),
    re_path(r'dispatch/(?P<pk>[0-9]+)/$', views.dispatch, name='dispatch_drone'),

    #warehouse personnel
    re_path(r'priority_queue/$', views.PriorityQueueView.as_view(), name='priority_queue'),
    re_path(r'priority_queue/1/(?P<pk>[0-9]+)/$', views.processing_order, name='order_processing'),
    re_path(r'priority_queue/2/(?P<pk>[0-9]+)/$', views.order_processed, name='order_processed'),
    re_path(r'priority_queue/3/(?P<pk>[0-9]+)/$', views.download_shipping, name='download_shipping'),

]

templates/warehouse-personnel/Priorityqueue.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>View Orders</title>
    <link href="../../airsupply/static/airsupply/css/bootstrap.min.css" rel="stylesheet">
    <link href="../../airsupply/static/airsupply/css/font-awesome.min.css" rel="stylesheet">
    <link href="../../airsupply/static/airsupply/css/prettyPhoto.css" rel="stylesheet">
    <link href="../../airsupply/static/airsupply/css/price-range.css" rel="stylesheet">
    <link href="../../airsupply/static/airsupply/css/animate.css" rel="stylesheet">
	<link href="../../airsupply/static/airsupply/css/main.css" rel="stylesheet">
	<link href="../../airsupply/static/airsupply/css/responsive.css" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->       
    <link rel="shortcut icon" href="../../airsupply/static/airsupply/images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../../airsupply/static/airsupply/images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../../airsupply/static/airsupply/images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../../airsupply/static/airsupply/images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../../airsupply/static/airsupply/images/ico/apple-touch-icon-57-precomposed.png">
</head><!--/head-->

<body>
	<header id="header"><!--header-->
		
		<div class="header-middle"><!--header-middle-->
			<div class="container">
				<div class="row">
					<div class="col-sm-4">
						<div class="logo pull-left">
							<a href="index.html"><img src="../../airsupply/static/airsupply/images/home/logo.png" alt="" /></a>
						</div>
					</div>
					<div class="col-sm-8">
						<div class="shop-menu pull-right">
							<ul class="nav navbar-nav">
								<li><a href="account.html"><i class="fa fa-user"></i> Account</a></li>
								<li><a href="login.html"><i class="fa fa-sign-out"></i> Logout</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-middle-->
	
		<div class="header-bottom"><!--header-bottom-->
			<div class="container">
				<div class="row">
					<div class="col-sm-9">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>
						<!-- in future iterations
						<div class="mainmenu pull-left">
							<ul class="nav navbar-nav collapse navbar-collapse">
								<li><a href="shop.html">Browse</a></li>
								<li><a href="cart.html">Cart</a></li>
								<li><a href="view-orders.html">View Orders</a></li>
							</ul>
						</div>
						-->
					</div>
				</div>
			</div>
		</div><!--/header-bottom-->
	</header><!--/header-->

	<section id="cart_items">
		<div class="container">
			<!-- release in future iterations
			<div class="breadcrumbs">
				<ol class="breadcrumb">
				  <li><a href="#">Home</a></li>
				  <li class="active">Shopping Cart</li>
				</ol>
			</div>
			-->
			<div class="table-responsive cart_info">
				<table class="table table-condensed">
					<thead>
						<tr class="cart_menu">
							<td class="image">Clinic</td>
							<td class="description">Order ID</td>
							<td class="price">Priority</td>
							<td class="quantity">Weight</td>
							<td></td>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td class="cart_product">
								<h4>Clinic 1</h4>
							</td>
							<td class="cart_description">
								<h4>Order_6789</h4>
							</td>
							<td class="cart_price">
								<p>High</p>
							</td>
							<td class="cart_quantity">
								<p class="cart_total_price">2.1kg</p>
							</td>
							<td class="cart_total">
								<button type="submit" class="btn btn-default">Process</button>
							</td>
						</tr>

						
						<tr>
							<td class="cart_product">
								<h4>Clinic 1</h4>
							</td>
							<td class="cart_description">
								<h4>Order_1234</h4>
							</td>
							<td class="cart_price">
								<p>High</p>
							</td>
							<td class="cart_quantity">
								<p class="cart_total_price">20.0kg</p>
							</td>
							<td class="cart_total">
								
							</td>
						</tr>

						<tr>
							<td class="cart_product">
								<h4>Clinic 2</h4>
							</td>
							<td class="cart_description">
								<h4>Order_5678</h4>
							</td>
							<td class="cart_price">
								<p>Medium</p>
							</td>
							<td class="cart_quantity">
								<p class="cart_total_price">3.4kg</p>
							</td>
							<td class="cart_total">
								
							</td>
						</tr>

						<tr>
							<td class="cart_product">
								<h4>Clinic 3</h4>
							</td>
							<td class="cart_description">
								<h4>Order_9012</h4>
							</td>
							<td class="cart_price">
								<p>Low</p>
							</td>
							<td class="cart_quantity">
								<p class="cart_total_price">17.9kg</p>
							</td>
							<td class="cart_total">
								
							</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</section> <!--/#cart_items-->

	
    <script src="js/jquery.js"></script>
	<script src="js/bootstrap.min.js"></script>
	<script src="js/jquery.scrollUp.min.js"></script>
    <script src="js/jquery.prettyPhoto.js"></script>
    <script src="js/main.js"></script>
</body>
</html>

templates/warehouse-personnel/navbar.html
    <div class="header-bottom"><!--header-bottom-->
        <div class="container">
            <div class="row">
                <div class="col-sm-9">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="mainmenu pull-left">
                        <ul class="nav navbar-nav collapse navbar-collapse">
                            <!-- add in future iteration
                            <li><a href="index.html" class="active">Home</a></li>
                            -->
                            <li><a href="{% url 'airsupply:priority_queue' %}">Priority Queue</a></li>
                            <!-- keeping in case needed
                            <li class="dropdown"><a href="#">Shop<i class="fa fa-angle-down"></i></a>
                                <ul role="menu" class="sub-menu">
                                    <li><a href="shop.html">Products</a></li>
                                    <li><a href="product-details.html">Product Details</a></li>
                                    <li><a href="checkout.html">Checkout</a></li>
                                    <li><a href="cart.html">Cart</a></li>
                                    <li><a href="login.html">Login</a></li>
                                </ul>
                            </li>
                            -->
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-bottom-->
</header><!--/header-->

templates/warehouse-personnel/navbarWP.html
    <div class="header-bottom"><!--header-bottom-->
        <div class="container">
            <div class="row">
                <div class="col-sm-9">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="mainmenu pull-left">
                        <ul class="nav navbar-nav collapse navbar-collapse">
                            <!-- add in future iteration
                            <li><a href="index.html" class="active">Home</a></li>
                            -->
                            <li><a href="{% url 'airsupply:priority_queue' %}">Priority Queue</a></li>
                            <!-- keeping in case needed
                            <li class="dropdown"><a href="#">Shop<i class="fa fa-angle-down"></i></a>
                                <ul role="menu" class="sub-menu">
                                    <li><a href="shop.html">Products</a></li>
                                    <li><a href="product-details.html">Product Details</a></li>
                                    <li><a href="checkout.html">Checkout</a></li>
                                    <li><a href="cart.html">Cart</a></li>
                                    <li><a href="login.html">Login</a></li>
                                </ul>
                            </li>
                            -->
                        </ul>
                    </div>
                </div>
                <div class="col-sm-3">
                   <ul class="nav navbar-nav navbar-right">
                     <li><a href="{% url 'airsupply:cart' %}"><span class="glyphicon glyphicon-shopping-cart"></span> Proceed to Checkout</a></li>
                   </ul>
                </div>
            </div>
        </div>
    </div><!--/header-bottom-->
</header><!--/header-->

templates/warehouse-personnel/pdf.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <title>Shipping Label - {{ id }}</title>
        <style type="text/css">
            body {
                font-weight: 200;
                font-size: 14px;
            }
            .header {
                font-size: 20px;
                font-weight: 100;
                text-align: center;
                color: #007cae;
            }
            .title {
                font-size: 22px;
                font-weight: 700;
               /* text-align: right;*/
               padding: 10px 20px 0px 20px;
                margin-bottom: 0;
            }
            .title span {
                color: #007cae;
            }
            .subtitle{
                font-size: 14px;
                margin-top: 0px;
            }
            .details {
                padding: 10px 20px 0px 20px;
                text-align: left !important;
                /*margin-left: 40%;*/
            }
            .hrItem {
                border: none;
                height: 1px;
                /* Set the hr color */
                color: #333; /* old IE */
                background-color: #fff; /* Modern Browsers */
            }
            table{
                margin: 50px auto;
            }
            table, th, td {
               border: 1px solid black;
            }
            td{
                padding: 5px 10px;
            }
            th{
                padding: 10px;
                background: #aaaaaa;
            }
            .item-id{
                width: 10px;
                text-align: center;
            }

        </style>
    </head>
    <body>
        <div class='wrapper'>
            <div class='header'>
                <p class='title'>Air Supply - Pilot</p>
                <p class='subtitle'>Shipping Details</p>
            </div>
        <div>
        <div class='details'>
            <b>Order ID:</b> {{ id }} <br/>
            <b>Clinic:</b> {{ name }}  <br/>
            <b>Priority:</b> {{ priority }} <br/>
            <hr class='hrItem' />
        </div>
        <table>
            <thead>
                <th class="item-id" style="width:150px">Item ID</th>
                <th>Name</th>
                <th style="width:100px; text-align: center">Quantity</th>
            </thead>
            <tbody>
                {% for item in all_items.all %}
                    <tr>
                        <td class="item-id">{{ item.item.id }}</td>
                        <td>{{ item.item.description }}</td>
                        <td>{{ item.quantity }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <hr class='hrItem' />
    </div>
    </body>
</html>

templates/warehouse-personnel/priority-queue.html
{% extends 'base.html' %}

{% block navbar %}
{% endblock %}

{% block body %}
	<section id="cart_items">
		<div class="container">
			<!-- release in future iterations
			<div class="breadcrumbs">
				<ol class="breadcrumb">
				  <li><a href="#">Home</a></li>
				  <li class="active">Shopping Cart</li>
				</ol>
			</div>
			-->
			<div class="table-responsive cart_info">
				<table class="table table-condensed" id="priority-list-table">
					<thead>
						<tr class="cart_menu">
                            <td></td>
							<td class="image">Clinic</td>
							<td class="description">Order ID</td>
							<td class="price">Priority</td>
							<td class="quantity">Weight</td>
							<td></td>
						</tr>
					</thead>
					<tbody>
                        {% for order in all_orders %}
                            <tr style="cursor: pointer">
                                <td class="expandCollapseIcon"><i class="glyphicon glyphicon-plus-sign" title="Click to see or hide details!"></i></td>
                                <td class="cart_product">
                                    <h4>{{ order.clinicManager.clinic.name }}</h4>
                                </td>
                                <td class="cart_description">
                                    <h4>{{ order.id }}</h4>
                                </td>
                                <td class="cart_price">
                                    <p>{{ order.priority }}</p>
                                </td>
                                <td class="cart_quantity">
                                    <p class="cart_total_price">{{ order.totalWeight }}kg</p>
                                </td>
                                <td class="cart_total">
                                    {% if forloop.first %}
                                    <button class="btn btn-default process-order-btn">Process this Order</button>
                                    {% endif %}
                                </td>
                            </tr>
                            <tr>
                                <td colspan="6" class="item-details">
                                    <div class="toggleWrapper">
                                        <div class="row">
                                            <div class="col-xs-1 itemTitle">No.</div>
                                            <div class="col-xs-2 itemTitle center">Item ID</div>
                                            <div class="col-xs-6 itemTitle">Description</div>
                                            <div class="col-xs-2 itemTitle center">Quantity</div>
                                        </div>
                                        {% for item in order.items.all %}
                                            <div class="row">
                                                <div class="col-xs-1">{{ forloop.counter }}</div>
                                                <div class="col-xs-2 center">{{ item.item.id }}</div>
                                                <div class="col-xs-6">{{ item.item.description }}</div>
                                                <div class="col-xs-2 center">{{ item.quantity }}</div>
                                            </div>
                                        {% endfor %}
                                        <a class="btn btn-default order-processed-btn" href={% url 'airsupply:order_processed' order.id %}>&#x2714; Order Processed</a>
                                        <a class="btn btn-default down-shipping-btn" target="_blank" href={% url 'airsupply:download_shipping' order.id %}>Download Shipping Label</a>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</section> <!--/#cart_items-->
{% endblock %}