ASP/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from airsupply import views

urlpatterns = [

    path('main/', include('airsupply.urls')),
    path('admin/', admin.site.urls, name='admin_page'),


]

airsupply/urls.py
from django.urls import path, re_path
from . import views

app_name = 'airsupply'

urlpatterns = [

    #users
    re_path(r'^$', views.UserLoginView.as_view(), name='login'),
    re_path(r'^logout/$', views.logout_user, name='logout'),
    path('account/', views.UserAccount.as_view(), name='account'),
    re_path(r'^register/(?P<usernameb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.UserRegisterView.as_view(), name='register'),
    re_path(r'^register/$', views.UserRegisterView.as_view(), name='confirm_registration'),
    re_path(r'^forgot_password/$', views.UserForgotPassword.as_view(), name='forgot_password'),

    #clinic manager
    path('browse/', views.BrowseView.as_view(), name='browse'),
    re_path(r'browse/(?P<catID>[0-9]+)/$', views.BrowseView.as_view(), name='browse_cat'),
    path('cart/', views.CartView.as_view(),  name='cart'),
    path('my_orders/', views.OrderView.as_view(), name='my_orders'),
    re_path(r'my_orders/cancel/(?P<pk>[0-9]+)/$', views.cancelOrder, name='cancel_order'),
    re_path(r'my_orders/receive/(?P<pk>[0-9]+)/$', views.receiveOrder, name='receive_order'),
    path('cart/add/', views.cart_add, name='cart_add'),  # Change main.js too if URL is changed
    path('cart/checkout/', views.cart_checkout, name='cart_checkout'),
    re_path(r'order/(?P<pk>[0-9]+)/$', views.OrderDetailView.as_view(), name='view_order_details'),
    re_path(r'remove_item/(?P<order_pk>[0-9]+)/(?P<item_pk>[0-9]+)/$', views.delete_item, name='remove_item'),

    #dispatcher
    path('dispatch/', views.DispatchView.as_view(), name='dispatch_view'),
    re_path(r'dispatch/itinerary/(?P<pk>[0-9]+)/$', views.get_itinerary, name='get_itinerary'),
    re_path(r'dispatch/(?P<pk>[0-9]+)/$', views.dispatch, name='dispatch_drone'),

    #warehouse personnel
    re_path(r'priority_queue/$', views.PriorityQueueView.as_view(), name='priority_queue'),
    re_path(r'priority_queue/1/(?P<pk>[0-9]+)/$', views.processing_order, name='order_processing'),
    re_path(r'priority_queue/2/(?P<pk>[0-9]+)/$', views.order_processed, name='order_processed'),
    re_path(r'priority_queue/3/(?P<pk>[0-9]+)/$', views.download_shipping, name='download_shipping'),

]

templates/clinic-manager/browse.html
{% extends 'base.html' %}

{% block navbar %}
    {% include 'clinic-manager/navbar.html' %}
{% endblock %}

{% block body %}
	<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						
						<div class="brands_products"><!--brands_products-->
							<h2>Search</h2>
							<form class="form-inline md-form form-sm mt-0" action="{% url 'airsupply:browse' %}" method="get">
                              <input class="form-control form-control-sm ml-3 w-75" type="text" name="itemDesc" placeholder="&#xF002; &nbsp; Search for an item..." aria-label="Search" style="font-family:Arial, FontAwesome">
                            </form>
						</div><!--/brands_products-->

						<div class="brands_products"><!--brands_products-->
							<h2>Category</h2>
							<div class="brands-name">
								<ul class="nav nav-pills nav-stacked">
                                    {% for category in categories %}
                                        <li><a href="{% url 'airsupply:browse_cat' category.id %}"> <span class="pull-right">({{ catSizes|get_item:category }})</span>{{ category.name }}</a></li>
                                    {% endfor %}
								</ul>
							</div>
						</div><!--/brands_products-->
						
						<!-- will show in future iterations
						<div class="price-range">
							<h2>Weight Range</h2>
							<div class="well text-center">
								 <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="25" data-slider-step="1" data-slider-value="[0,25]" id="sl2" ><br />
								 <b class="pull-left">0 kg</b> <b class="pull-right">25 kg</b>
							</div>
						</div>
						-->
						
					</div>
				</div>
				
				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center">Medical Supplies</h2>
                        {% if all_items.categorized %}
                            <a href="{% url "airsupply:browse" %}" class="btn btn-default clr-filter-btn">Clear Filter</a>
                        {% endif %}
                        {% for item in all_items %}
						<div class="product-wrapper">
							<div class="col-sm-3" style="text-align: center;">
								<img src="{{ item.imageUrl }}" class="img-responsive product-img">
								<span class="product-id"><b>Item ID:</b> {{ item.id }}</span>
							</div>
							<div class="col-sm-7">
								<span class="product-name">{{ item.description }}</span>
								<span class="product-description">Category: {{ item.category }}.<br/>Weight: {{ item.weight }}kg</span>
							</div>
							<div class="col-sm-2"  style="text-align: center; padding-top: 20px;">
                                <form action="#" method="post">
                                    {% csrf_token %}
                                    Qty:
                                    <div class="cart_quantity_button">
                                        <a class="cart_quantity_up" href="javascript:void(0)"> + </a>
                                        <input class="cart_quantity_input" type="text" name="qty" value="1" autocomplete="off" size="2">
                                        <a class="cart_quantity_down" href="javascript:void(0)"> - </a>
                                    </div>
                                    <input type="hidden" name="itemID" value="{{ item.id }}">
                                    <input type="submit"  class="btn btn-default add-to-cart" value="&#xf07a; &nbsp; Add to cart" style="font-family:Arial, FontAwesome">
                                </form>
							</div>
						</div>
                        {% endfor %}

					</div><!--features_items-->
				</div>
			</div>
		</div>
	</section>
	

{% endblock %}

templates/clinic-manager/cart.html
{% extends 'base.html' %}

{% block navbar %}
    {% include 'clinic-manager/navbar.html' %}
{% endblock %}

{% block body %}
	<div class="container">
		<section id="cart_items" class="col-sm-9">

			<!-- release in future iterations
			<div class="breadcrumbs">
				<ol class="breadcrumb">
				  <li><a href="#">Home</a></li>
				  <li class="active">Shopping Cart</li>
				</ol>
			</div>
			-->


			<div class="table-responsive cart_info">


				<table class="table table-condensed">
					<thead>
						<tr class="cart_menu">
							<td class="image">Item</td>
							<td class="description"></td>
							<td class="price">Weight</td>
							<td class="quantity">Quantity</td>
							<td class="total">Total Weight</td>
                            {% if ordered == 'FALSE' %}
							<td></td>
                            {% endif %}
						</tr>
					</thead>
					<tbody>
                        {% for item in all_items %}
                            <tr>
                                <td class="cart_product">
                                    <a href=""><img src="{{ item.item.imageUrl }}" alt=""></a>
                                </td>
                                <td class="cart_description">
                                    <h4><a href="">{{ item.item.description }}</a></h4>
                                    <p>Product ID: {{ item.item.id }}</p>
                                </td>
                                <td class="cart_price">
                                    <p>{{ item.item.weight }}</p>
                                </td>
                                <td class="cart_quantity">
                                    <p>{{ item.quantity }}</p>
                                </td>
                                <td class="cart_total">
                                    <p class="cart_total_price">{{ weights|get_item:item }}</p>
                                </td>
                                {% if ordered == 'FALSE' %}
                                <td class="cart_delete">
                                    <a class="cart_quantity_delete" href="{% url 'airsupply:remove_item' order_id item.id %}"><i class="fa fa-times"></i></a>
                                </td>
                                {% endif %}
                            </tr>
                        {% endfor %}
					</tbody>
				</table>
			</div>
		</section>

		<section id="do_action" class="col-sm-3">
				<div class="total_area">
                    {% if ordered == 'FALSE' %}
					    <span style="float:left;">Priority:</span>
                        <select name="priority" form="checkoutForm" class="cart_priority_selector">
                            <option value="High">High</option>
                            <option value="Medium">Medium</option>
                            <option value="Low">Low</option>
                        </select>
                        <p>Cart Total Weight: {{ totalWeight }}</p>
                        <form action="{% url 'airsupply:cart_checkout' %}" method="post" id="checkoutForm">
                            {% csrf_token %}
                            <input class="btn btn-default check_out" type="submit" value="Checkout Cart">
                        </form>
                    {% else %}
                        <span style="float:left;">Date: {{ date }}</span><br>
                        <span style="float:left;">Priority: {{ priority }}</span><br>
                        <p>Cart Total Weight: {{ totalWeight }}</p>
                    {% endif %}
				</div>


		</section><!--/#do_action-->
	</div>

{% endblock %}

templates/clinic-manager/navbar.html
    <div class="header-bottom"><!--header-bottom-->
        <div class="container">
            <div class="row">
                <div class="col-sm-9">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="mainmenu pull-left">
                        <ul class="nav navbar-nav collapse navbar-collapse">
                            <!-- add in future iteration
                            <li><a href="index.html" class="active">Home</a></li>
                            -->
                            <li><a href="{% url 'airsupply:browse' %}">Browse</a></li>
                            <li><a href="{% url 'airsupply:cart' %}">Cart</a></li>
                            <li><a href="{% url 'airsupply:my_orders' %}">View Orders</a></li>
                            <!-- keeping in case needed
                            <li class="dropdown"><a href="#">Shop<i class="fa fa-angle-down"></i></a>
                                <ul role="menu" class="sub-menu">
                                    <li><a href="shop.html">Products</a></li>
                                    <li><a href="product-details.html">Product Details</a></li>
                                    <li><a href="checkout.html">Checkout</a></li>
                                    <li><a href="cart.html">Cart</a></li>
                                    <li><a href="login.html">Login</a></li>
                                </ul>
                            </li>
                            -->
                        </ul>
                    </div>
                </div>
                <div class="col-sm-3">
                   <ul class="nav navbar-nav navbar-right">
                     <li><a href="{% url 'airsupply:cart' %}"><span class="glyphicon glyphicon-shopping-cart"></span> Proceed to Checkout</a></li>
                   </ul>
                </div>
            </div>
        </div>
    </div><!--/header-bottom-->
</header><!--/header-->

templates/clinic-manager/view-orders.html
{% extends 'base.html' %}

{% block navbar %}
    {% include 'clinic-manager/navbar.html' %}
{% endblock %}

{% block body %}
	<section id="cart_items">
		<div class="container">
			<!-- release in future iterations
			<div class="breadcrumbs">
				<ol class="breadcrumb">
				  <li><a href="#">Home</a></li>
				  <li class="active">Shopping Cart</li>
				</ol>
			</div>
			-->
			<div class="table-responsive cart_info">
				<table class="table table-condensed">
					<thead>
						<tr class="cart_menu">
							<td class="order-no">Order #</td>
							<td class="oder-status">Status</td>
							<td class="order-cancel"></td>
							<td class="order-date">Date Ordered</td>
						</tr>
					</thead>
					<tbody>
                        {% for order in all_orders %}
                            <tr>
                                <td class="order_no">
                                    <h4><a href="{% url 'airsupply:view_order_details' order.id %}">00000{{ order.id }}</a></h4>
                                </td>
                                <td class="order_status">
                                    <p>{{ order.status }}</p>
                                </td>
                                <td class="order_cancel">
                                    {% if order.status == 'Queued for Processing' %}
                                        <a href="{% url 'airsupply:cancel_order' order.id %}" class="btn btn-default">Cancel Order</a>
                                    {% elif order.status == 'Dispatched' %}
                                        <a href="{% url 'airsupply:receive_order' order.id %}" class="btn btn-default">Received Order</a>
                                    {% endif %}
                                </td>
                                <td class="order_date">
                                    <p>{{ order.timeOrdered }}</p>
                                </td>
                            </tr>
                        {% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</section> <!--/#cart_items-->



{% endblock %}