ASP/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from airsupply import views

urlpatterns = [

    path('main/', include('airsupply.urls')),
    path('admin/', admin.site.urls, name='admin_page'),


]

airsupply/urls.py
from django.urls import path, re_path
from . import views

app_name = 'airsupply'

urlpatterns = [

    #users
    re_path(r'^$', views.UserLoginView.as_view(), name='login'),
    re_path(r'^logout/$', views.logout_user, name='logout'),
    path('account/', views.UserAccount.as_view(), name='account'),
    re_path(r'^register/(?P<usernameb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.UserRegisterView.as_view(), name='register'),
    re_path(r'^register/$', views.UserRegisterView.as_view(), name='confirm_registration'),
    re_path(r'^forgot_password/$', views.UserForgotPassword.as_view(), name='forgot_password'),

    #clinic manager
    path('browse/', views.BrowseView.as_view(), name='browse'),
    re_path(r'browse/(?P<catID>[0-9]+)/$', views.BrowseView.as_view(), name='browse_cat'),
    path('cart/', views.CartView.as_view(),  name='cart'),
    path('my_orders/', views.OrderView.as_view(), name='my_orders'),
    re_path(r'my_orders/cancel/(?P<pk>[0-9]+)/$', views.cancelOrder, name='cancel_order'),
    re_path(r'my_orders/receive/(?P<pk>[0-9]+)/$', views.receiveOrder, name='receive_order'),
    path('cart/add/', views.cart_add, name='cart_add'),  # Change main.js too if URL is changed
    path('cart/checkout/', views.cart_checkout, name='cart_checkout'),
    re_path(r'order/(?P<pk>[0-9]+)/$', views.OrderDetailView.as_view(), name='view_order_details'),
    re_path(r'remove_item/(?P<order_pk>[0-9]+)/(?P<item_pk>[0-9]+)/$', views.delete_item, name='remove_item'),

    #dispatcher
    path('dispatch/', views.DispatchView.as_view(), name='dispatch_view'),
    re_path(r'dispatch/itinerary/(?P<pk>[0-9]+)/$', views.get_itinerary, name='get_itinerary'),
    re_path(r'dispatch/(?P<pk>[0-9]+)/$', views.dispatch, name='dispatch_drone'),

    #warehouse personnel
    re_path(r'priority_queue/$', views.PriorityQueueView.as_view(), name='priority_queue'),
    re_path(r'priority_queue/1/(?P<pk>[0-9]+)/$', views.processing_order, name='order_processing'),
    re_path(r'priority_queue/2/(?P<pk>[0-9]+)/$', views.order_processed, name='order_processed'),
    re_path(r'priority_queue/3/(?P<pk>[0-9]+)/$', views.download_shipping, name='download_shipping'),

]

templates/dispatcher/dispatch-queue.html
{% extends 'base.html' %}

{% block body %}


	<div class="container">
		<section id="cart_items">
		
			<!-- release in future iterations
			<div class="breadcrumbs">
				<ol class="breadcrumb">
				  <li><a href="#">Home</a></li>
				  <li class="active">Shopping Cart</li>
				</ol>
			</div>
			-->
			<div class="table-responsive cart_info dispatch_info">
				<table class="table table-condensed">
					<thead>
						<tr class="cart_menu">
							<!--<td class="drone">Drone ID</td>-->
							<td class="orders">Orders</td>
							<!--<td class="weight"></td>-->
							<td class="dispatch_options">Options</td>
						</tr>
					</thead>
					<tbody>

                    {% for droneload in all_droneloads %}
                        <tr {% if forloop.first %} class="top_drone" {% endif %}>
							<!--<td class="drone_col verticalColumn">-->
								<!--<p class="drone_id" title="To be added in real iteration">-->
									<!---->
								<!--</p>-->
							<!--</td>-->
							<td class="cart_description orders_col">
								<h4>Orders to be loaded:</h4>
                                {% for order in droneload.orders.all %}
                                    <div class="row">
                                        <div class="col-xs-1"><br>{{ forloop.counter }}.</div>
                                        <div class="col-xs-8 order_wrapper"><b>{{ order.id }}</b><br>{{ order.clinicManager.clinic.name }}</div>
                                        <div class="col-xs-2 weight_col"><br>{{ order.totalWeight }} kg</div>
                                    </div>
                                {% endfor %}
                                    <div class="row">
                                        <div class="col-xs-8"></div>
                                        <div class="col-xs-1 plus_sign">+</div>
                                        <div class="col-xs-2 weight_col total_weight">{{ dlWeights|get_item:droneload }} kg</div>
                                    </div>

							</td>
							<td class="cart_quantity dispatch_col">
								<a href="{% url 'airsupply:get_itinerary' droneload.id %}" class="btn btn-default add-to-cart"><i class="fa fa-download"></i> Download Itinerary</a>
								<a href="{% url 'airsupply:dispatch_drone' droneload.id %}" class="btn btn-default dispatch"><i class="fa fa-check"></i> Dispatch Drone</a>
							</td>
						</tr>
                    {% endfor %}


					</tbody>
				</table>
			</div>
		</section> 
	</div>



{% endblock %}

templates/dispatcher/dispatchQueue.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Cart | E-Shopper</title>
    <link href="../../airsupply/static/airsupply/css/bootstrap.min.css" rel="stylesheet">
    <link href="../../airsupply/static/airsupply/css/font-awesome.min.css" rel="stylesheet">
    <link href="../../airsupply/static/airsupply/css/prettyPhoto.css" rel="stylesheet">
    <link href="../../airsupply/static/airsupply/css/price-range.css" rel="stylesheet">
    <link href="../../airsupply/static/airsupply/css/animate.css" rel="stylesheet">
	<link href="../../airsupply/static/airsupply/css/main.css" rel="stylesheet">
	<link href="../../airsupply/static/airsupply/css/responsive.css" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->       
    <link rel="shortcut icon" href="../../airsupply/static/airsupply/images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../../airsupply/static/airsupply/images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../../airsupply/static/airsupply/images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../../airsupply/static/airsupply/images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../../airsupply/static/airsupply/images/ico/apple-touch-icon-57-precomposed.png">
</head><!--/head-->

<body>
	<header id="header"><!--header-->
		
		<div class="header-middle"><!--header-middle-->
			<div class="container">
				<div class="row">
					<div class="col-sm-4">
						<div class="logo pull-left">
							<a href="index.html"><img src="../../airsupply/static/airsupply/images/home/logo.png" alt="" /></a>
						</div>
					</div>
					<div class="col-sm-8">
						<div class="shop-menu pull-right">
							<ul class="nav navbar-nav">
								<li><a href="account.html"><i class="fa fa-user"></i> Account</a></li>
								<li><a href="login.html"><i class="fa fa-sign-out"></i> Logout</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-middle-->
	
		<div class="header-bottom"><!--header-bottom-->
			<div class="container">
				<div class="row">
					<div class="col-sm-9">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>
						<!-- in future iterations
						<div class="mainmenu pull-left">
							<ul class="nav navbar-nav collapse navbar-collapse">
								<li><a href="shop.html">Browse</a></li>
							</ul>
						</div>
						-->
					</div>
				</div>
			</div>
		</div><!--/header-bottom-->
	</header><!--/header-->

	<div class="container">
		<section id="cart_items">
		
			<!-- release in future iterations
			<div class="breadcrumbs">
				<ol class="breadcrumb">
				  <li><a href="#">Home</a></li>
				  <li class="active">Shopping Cart</li>
				</ol>
			</div>
			-->
			<div class="table-responsive cart_info dispatch_info">
				<table class="table table-condensed">
					<thead>
						<tr class="cart_menu">
							<td class="drone">Drone ID</td>
							<td class="orders">Orders</td>
							<!--<td class="weight"></td>-->
							<td class="dispatch_options">Options</td>
						</tr>
					</thead>
					<tbody>
						<tr class="top_drone">
							<td class="drone_col verticalColumn">
								<p class="drone_id">
									123456
								</p>
							</td>
							<td class="cart_description orders_col">
								<h4>Orders to be loaded:</h4>
								<div class="row">
									<div class="col-xs-1"><br>1.</div>
									<div class="col-xs-8 order_wrapper"><b>123456</b><br>Jockey Club Clinic</div>
									<div class="col-xs-2 weight_col"><br>3kg</div>
								</div>

								<div class="row">
									<div class="col-xs-1"><br>2.</div>
									<div class="col-xs-8 order_wrapper"><b>665544</b><br>Clinic No 2</div>
									<div class="col-xs-2 weight_col"><br>4kg</div>
								</div>

								<div class="row">
									<div class="col-xs-1"><br>3.</div>
									<div class="col-xs-8 order_wrapper"><b>113346</b><br>Another Clinic</div>
									<div class="col-xs-2 weight_col"><br>5.5kg</div>
								</div>
								<div class="row">
									<div class="col-xs-8"></div>
									<div class="col-xs-1 plus_sign">+</div>
									<div class="col-xs-2 weight_col total_weight">12.5kg</div>
								</div>
							</td>
							<!--<td class="cart_price weight_col">
								<h4></h4>
								<ol>
									<li><b>3.5kg</b><br> </li>
									<li><b>5.8kg</b><br> </li>
									<li><b>2.2kg</b><br> </li>
								</ol>
							</td>-->
							<td class="cart_quantity dispatch_col">
								<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-download"></i> Downlaod Itinerary</a>
								<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-check"></i> Dispatch Drone</a>
							</td>
						</tr>
						<tr>
							<td class="drone_col verticalColumn">
								<p class="drone_id">
									123456
								</p>
							</td>
							<td class="cart_description orders_col">
								<h4>Orders to be loaded:</h4>
								<div class="row">
									<div class="col-xs-1"><br>1.</div>
									<div class="col-xs-8 order_wrapper"><b>123456</b><br>Jockey Club Clinic</div>
									<div class="col-xs-2 weight_col"><br>3kg</div>
								</div>

								<div class="row">
									<div class="col-xs-1"><br>2.</div>
									<div class="col-xs-8 order_wrapper"><b>665544</b><br>Clinic No 2</div>
									<div class="col-xs-2 weight_col"><br>4kg</div>
								</div>

								<div class="row">
									<div class="col-xs-1"><br>3.</div>
									<div class="col-xs-8 order_wrapper"><b>113346</b><br>Another Clinic</div>
									<div class="col-xs-2 weight_col"><br>5.5kg</div>
								</div>
								<div class="row">
									<div class="col-xs-8"></div>
									<div class="col-xs-1 plus_sign">+</div>
									<div class="col-xs-2 weight_col total_weight">12.5kg</div>
								</div>
							</td>
							<!--<td class="cart_price weight_col">
								<h4></h4>
								<ol>
									<li><b>3.5kg</b><br> </li>
									<li><b>5.8kg</b><br> </li>
									<li><b>2.2kg</b><br> </li>
								</ol>
							</td>-->
							<td class="cart_quantity dispatch_col">
								<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-download"></i> Downlaod Itinerary</a>
								<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-check"></i> Dispatch Drone</a>
							</td>
						</tr>
						<tr>
							<td class="drone_col verticalColumn">
								<p class="drone_id">
									123456
								</p>
							</td>
							<td class="cart_description orders_col">
								<h4>Orders to be loaded:</h4>
								<div class="row">
									<div class="col-xs-1"><br>1.</div>
									<div class="col-xs-8 order_wrapper"><b>123456</b><br>Jockey Club Clinic</div>
									<div class="col-xs-2 weight_col"><br>3kg</div>
								</div>

								<div class="row">
									<div class="col-xs-1"><br>2.</div>
									<div class="col-xs-8 order_wrapper"><b>665544</b><br>Clinic No 2</div>
									<div class="col-xs-2 weight_col"><br>4kg</div>
								</div>

								<div class="row">
									<div class="col-xs-1"><br>3.</div>
									<div class="col-xs-8 order_wrapper"><b>113346</b><br>Another Clinic</div>
									<div class="col-xs-2 weight_col"><br>5.5kg</div>
								</div>
								<div class="row">
									<div class="col-xs-8"></div>
									<div class="col-xs-1 plus_sign">+</div>
									<div class="col-xs-2 weight_col total_weight">12.5kg</div>
								</div>
							</td>
							<!--<td class="cart_price weight_col">
								<h4></h4>
								<ol>
									<li><b>3.5kg</b><br> </li>
									<li><b>5.8kg</b><br> </li>
									<li><b>2.2kg</b><br> </li>
								</ol>
							</td>-->
							<td class="cart_quantity dispatch_col">
								<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-download"></i> Downlaod Itinerary</a>
								<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-check"></i> Dispatch Drone</a>
							</td>
						</tr>


					</tbody>
				</table>
			</div>
		</section> 
	</div>


    <script src="js/jquery.js"></script>
	<script src="js/bootstrap.min.js"></script>
	<script src="js/jquery.scrollUp.min.js"></script>
    <script src="js/jquery.prettyPhoto.js"></script>
    <script src="js/main.js"></script>
</body>
</html>

templates/dispatcher/navbar.html
    <div class="header-bottom"><!--header-bottom-->
        <div class="container">
            <div class="row">
                <div class="col-sm-9">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="mainmenu pull-left">
                        <ul class="nav navbar-nav collapse navbar-collapse">
                            <!-- add in future iteration
                            <li><a href="index.html" class="active">Home</a></li>
                            -->
                            <li><a href="{% url 'airsupply:dispatch_view' %}">Dispatch Queue</a></li>
                            <!-- keeping in case needed
                            <li class="dropdown"><a href="#">Shop<i class="fa fa-angle-down"></i></a>
                                <ul role="menu" class="sub-menu">
                                    <li><a href="shop.html">Products</a></li>
                                    <li><a href="product-details.html">Product Details</a></li>
                                    <li><a href="checkout.html">Checkout</a></li>
                                    <li><a href="cart.html">Cart</a></li>
                                    <li><a href="login.html">Login</a></li>
                                </ul>
                            </li>
                            -->
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-bottom-->
</header><!--/header-->

templates/dispatcher/navbarD.html
    <div class="header-bottom"><!--header-bottom-->
        <div class="container">
            <div class="row">
                <div class="col-sm-9">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="mainmenu pull-left">
                        <ul class="nav navbar-nav collapse navbar-collapse">
                            <!-- add in future iteration
                            <li><a href="index.html" class="active">Home</a></li>
                            -->
                            <li><a href="{% url 'airsupply:dispatch_view' %}">Dispatch Queue</a></li>
                            <!-- keeping in case needed
                            <li class="dropdown"><a href="#">Shop<i class="fa fa-angle-down"></i></a>
                                <ul role="menu" class="sub-menu">
                                    <li><a href="shop.html">Products</a></li>
                                    <li><a href="product-details.html">Product Details</a></li>
                                    <li><a href="checkout.html">Checkout</a></li>
                                    <li><a href="cart.html">Cart</a></li>
                                    <li><a href="login.html">Login</a></li>
                                </ul>
                            </li>
                            -->
                        </ul>
                    </div>
                </div>
                <div class="col-sm-3">
                   <ul class="nav navbar-nav navbar-right">
                     <li><a href="{% url 'airsupply:cart' %}"><span class="glyphicon glyphicon-shopping-cart"></span> Proceed to Checkout</a></li>
                   </ul>
                </div>
            </div>
        </div>
    </div><!--/header-bottom-->
</header><!--/header-->