ASP/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from airsupply import views

urlpatterns = [

    path('main/', include('airsupply.urls')),
    path('admin/', admin.site.urls, name='admin_page'),


]

airsupply/urls.py
from django.urls import path, re_path
from . import views

app_name = 'airsupply'

urlpatterns = [

    #users
    re_path(r'^$', views.UserLoginView.as_view(), name='login'),
    re_path(r'^logout/$', views.logout_user, name='logout'),
    path('account/', views.UserAccount.as_view(), name='account'),
    re_path(r'^register/(?P<usernameb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.UserRegisterView.as_view(), name='register'),
    re_path(r'^register/$', views.UserRegisterView.as_view(), name='confirm_registration'),
    re_path(r'^forgot_password/$', views.UserForgotPassword.as_view(), name='forgot_password'),

    #clinic manager
    path('browse/', views.BrowseView.as_view(), name='browse'),
    re_path(r'browse/(?P<catID>[0-9]+)/$', views.BrowseView.as_view(), name='browse_cat'),
    path('cart/', views.CartView.as_view(),  name='cart'),
    path('my_orders/', views.OrderView.as_view(), name='my_orders'),
    re_path(r'my_orders/cancel/(?P<pk>[0-9]+)/$', views.cancelOrder, name='cancel_order'),
    re_path(r'my_orders/receive/(?P<pk>[0-9]+)/$', views.receiveOrder, name='receive_order'),
    path('cart/add/', views.cart_add, name='cart_add'),  # Change main.js too if URL is changed
    path('cart/checkout/', views.cart_checkout, name='cart_checkout'),
    re_path(r'order/(?P<pk>[0-9]+)/$', views.OrderDetailView.as_view(), name='view_order_details'),
    re_path(r'remove_item/(?P<order_pk>[0-9]+)/(?P<item_pk>[0-9]+)/$', views.delete_item, name='remove_item'),

    #dispatcher
    path('dispatch/', views.DispatchView.as_view(), name='dispatch_view'),
    re_path(r'dispatch/itinerary/(?P<pk>[0-9]+)/$', views.get_itinerary, name='get_itinerary'),
    re_path(r'dispatch/(?P<pk>[0-9]+)/$', views.dispatch, name='dispatch_drone'),

    #warehouse personnel
    re_path(r'priority_queue/$', views.PriorityQueueView.as_view(), name='priority_queue'),
    re_path(r'priority_queue/1/(?P<pk>[0-9]+)/$', views.processing_order, name='order_processing'),
    re_path(r'priority_queue/2/(?P<pk>[0-9]+)/$', views.order_processed, name='order_processed'),
    re_path(r'priority_queue/3/(?P<pk>[0-9]+)/$', views.download_shipping, name='download_shipping'),

]

templates/account.html
{% extends 'base.html' %}
{% block title %}
Account
{% endblock %}

{% block navbar %}
    {% if role == "Clinic Manager" %}
        {% include 'clinic-manager/navbar.html' %}
    {% elif role == "Warehouse Personnel" %}
        {% include 'warehouse-personnel/navbar.html' %}
     {% elif role == "Dispatcher" %}
        {% include 'dispatcher/navbar.html' %}
    {% endif %}
{% endblock %}

{% block body %}
	<section id="register-form"><!--form-->
		<div class="container">
			<div class="row">
				<div class="col-sm-6 col-sm-offset-3">
					<div class="signup-form"><!-- register-user change classname to regiter-form in css too -->
                        <h2>Your Account</h2>
						<form action="" id="account" method="post">
                            {% csrf_token %}
							<label>Role: </label> <label>{{role}}</label>
                            <br>
                            <label>Username: </label> <label> {{user.username}} </label>
							{% if role == "Clinic Manager" %}
                                <br>
                                <label>Clinic: </label> <input type="hidden" name="clinic" value="{{ user.clinicmanager.clinic.name }}"> <label> {{user.clinicmanager.clinic.name}} </label>
                            {% endif %}

                            <h2>You may change the details below.</h2>
                            {{ form.as_p }}

                        <button type="submit" class="btn btn-default">Update Account</button>
						</form>
					</div> <!-- /register-user -->
				</div>

			</div>
		</div>
	</section><!--/form-->

{% endblock %}

templates/base.html
{% extends 'base1.html' %}
{% block accountbar %}
    <div class="col-sm-10">
        <div class="shop-menu pull-right">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'airsupply:account' %}"><i class="fa fa-user"></i> Account</a></li>
                <li><a href="{% url 'airsupply:logout' %}"><i class="fa fa-sign-out"></i> Logout</a></li>
            </ul>
        </div>
    </div>

{% endblock %}

templates/base1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}Air Supply - Pilot{% endblock %}</title>

    {% load staticfiles %}

    <link href="{% static 'airsupply/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'airsupply/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'airsupply/css/prettyPhoto.css' %}" rel="stylesheet">
    <link href="{% static 'airsupply/css/price-range.css' %}" rel="stylesheet">
    <link href="{% static 'airsupply/css/animate.css' %}" rel="stylesheet">
	<link href="{% static 'airsupply/css/main.css' %}" rel="stylesheet">
	<link href="{% static 'airsupply/css/responsive.css' %}" rel="stylesheet">

    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="{% static 'airsupply/images/ico/favicon.ico' %}">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'airsupply/images/ico/apple-touch-icon-144-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'airsupply/images/ico/apple-touch-icon-114-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'airsupply/images/ico/apple-touch-icon-72-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" href="{% static 'airsupply/images/ico/apple-touch-icon-57-precomposed.png' %}">
</head>
<body>

    <header id="header"><!--header-->
        <div class="header-middle"><!--header-middle-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-2">
                        <div class="logo pull-left">
                            <a href="#">
                                {% load static %}
                                <img src="{% static 'airsupply/images/home/logo.png' %}" alt="" />
                            </a>
                        </div>
                        <!-- keeping for reference
                        <div class="btn-group pull-right">
                            <div class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                                    USA
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Canada</a></li>
                                    <li><a href="#">UK</a></li>
                                </ul>
                            </div>
                        </div>
                        -->
                    </div>
                    {% block accountbar %}
                    {% endblock %}
                </div>
            </div>
        </div><!--/header-middle-->

    {% block navbar %}
    {% endblock %}

    {% block body %}
    {% endblock %}

    <script src="{% static 'airsupply/js/jquery.js' %}"></script>
	<script src="{% static 'airsupply/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'airsupply/js/jquery.scrollUp.min.js' %}"></script>
	<script src="{% static 'airsupply/js/price-range.js' %}"></script>
    <script src="{% static 'airsupply/js/jquery.prettyPhoto.js' %}"></script>
    <script src="{% static 'airsupply/js/main.js' %}"></script>

</body>
</html>

templates/forgot-password.html
{% extends 'base1.html' %}
{% block title %}
Forgot Password
{% endblock %}

{% block body %}
	<section id="login-form"><!--form-->
		<div class="container">
			<div class="row">
				<div class="col-sm-6 col-sm-offset-3">
					<div class="login-form"><!-- register-user change classname to regiter-form in css too -->
						<h2>Please enter your username or email.</h2>
						<form action="" id="forgot-password" method="post"> <!-- implement the form action -->
                            {% csrf_token %}
							<input type="text" name='up' placeholder="Username or Email"/>
                            {% if error_message %}
                                <p class="error-msg">{{ error_message }}</p>
                            {% endif %}
							<button type="submit" class="btn btn-default">Submit</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section><!--/form-->
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Home | E-Shopper</title>
    <link href="../airsupply/static/airsupply/css/bootstrap.min.css" rel="stylesheet">
    <link href="../airsupply/static/airsupply/css/font-awesome.min.css" rel="stylesheet">
    <link href="../airsupply/static/airsupply/css/prettyPhoto.css" rel="stylesheet">
    <link href="../airsupply/static/airsupply/css/price-range.css" rel="stylesheet">
    <link href="../airsupply/static/airsupply/css/animate.css" rel="stylesheet">
	<link href="../airsupply/static/airsupply/css/main.css" rel="stylesheet">
	<link href="../airsupply/static/airsupply/css/responsive.css" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->       
    <link rel="shortcut icon" href="../airsupply/static/airsupply/images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../airsupply/static/airsupply/images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../airsupply/static/airsupply/images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../airsupply/static/airsupply/images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../airsupply/static/airsupply/images/ico/apple-touch-icon-57-precomposed.png">
</head><!--/head-->

<body>
	<header id="header"><!--header-->

		<div class="header-middle"><!--header-middle-->
			<div class="container">
				<div class="row">
					<div class="col-sm-4">
						<div class="logo pull-left">
							<a href="index.html"><img src="../airsupply/static/airsupply/images/home/logo.png" alt="" /></a>
						</div>
						<!-- keeping for reference
						<div class="btn-group pull-right">
							<div class="btn-group">
								<button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
									USA
									<span class="caret"></span>
								</button>
								<ul class="dropdown-menu">
									<li><a href="#">Canada</a></li>
									<li><a href="#">UK</a></li>
								</ul>
							</div>
						</div>
						-->
					</div>
					<div class="col-sm-8">
						<div class="shop-menu pull-right">
							<ul class="nav navbar-nav">
								<li><a href="account.html"><i class="fa fa-user"></i> Account</a></li>
								<li><a href="login.html"><i class="fa fa-sign-out"></i> Logout</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-middle-->
	
		<div class="header-bottom"><!--header-bottom-->
			<div class="container">
				<div class="row">
					<div class="col-sm-9">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>
						<div class="mainmenu pull-left">
							<ul class="nav navbar-nav collapse navbar-collapse">
								<!-- add in future iteration
								<li><a href="index.html" class="active">Home</a></li>
								-->
								<li><a href="shop.html">Browse</a></li>
								<li><a href="cart.html">Cart</a></li>
								<li><a href="cart.html">View Orders</a></li>
								<!-- keeping in case needed
								<li class="dropdown"><a href="#">Shop<i class="fa fa-angle-down"></i></a>
                                    <ul role="menu" class="sub-menu">
                                        <li><a href="shop.html">Products</a></li>
										<li><a href="product-details.html">Product Details</a></li> 
										<li><a href="checkout.html">Checkout</a></li> 
										<li><a href="cart.html">Cart</a></li> 
										<li><a href="login.html">Login</a></li> 
                                    </ul>
                                </li>
                           		-->
							</ul>
						</div>
					</div>
					<!-- will implement in future iterations
					<div class="col-sm-3">
						<div class="search_box pull-right">
							<input type="text" placeholder="Search"/>
						</div>
					</div>
					-->
				</div>
			</div>
		</div><!--/header-bottom-->
	</header><!--/header-->
	
	<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<div class="brands_products"><!--brands_products-->
							<h2>Category</h2>
							<div class="brands-name">
								<ul class="nav nav-pills nav-stacked">
									<li><a href="#"> <span class="pull-right">(50)</span>IV Fluids</a></li>
									<li><a href="javascript:void(0)" class="disabled"> <span class="pull-right">(56)</span>Category 2</a></li>
									<li><a href="javascript:void(0)" class="disabled"> <span class="pull-right">(27)</span>Category 3</a></li>
									<li><a href="javascript:void(0)" class="disabled"> <span class="pull-right">(32)</span>Category 4</a></li>
									<li><a href="javascript:void(0)" class="disabled"> <span class="pull-right">(5)</span>Category 5</a></li>
								</ul>
							</div>
						</div><!--/brands_products-->
						
						<!-- will show in future iterations
						<div class="price-range">
							<h2>Weight Range</h2>
							<div class="well text-center">
								 <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="25" data-slider-step="1" data-slider-value="[0,25]" id="sl2" ><br />
								 <b class="pull-left">0 kg</b> <b class="pull-right">25 kg</b>
							</div>
						</div>
						-->
						
					</div>
				</div>
				
				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center">Medical Supplies</h2>
						<div class="product-wrapper">
							<div class="col-sm-3" style="text-align: center;">
								<img src="../airsupply/static/airsupply/images/placeholder.png" class="img-responsive product-img">
								<span class="product-id"><b>Product ID:</b> 123456</span>
							</div>
							<div class="col-sm-7">
								<span class="product-name">Product Name</span>
								<span class="product-description">A long paragraph describing the product. its volume, type, etc with any additional things.</span>
							</div>
							<div class="col-sm-2"  style="text-align: center; padding-top: 20px;">
								Qty:
								<div class="cart_quantity_button">
									<a class="cart_quantity_up" href=""> + </a>
									<input class="cart_quantity_input" type="text" name="quantity" value="1" autocomplete="off" size="2">
									<a class="cart_quantity_down" href=""> - </a>
								</div>
								<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
							</div>
						</div>
						<div class="product-wrapper">
							<div class="col-sm-3" style="text-align: center;">
								<img src="../airsupply/static/airsupply/images/placeholder.png" class="img-responsive product-img">
								<span class="product-id"><b>Product ID:</b> 123456</span>
							</div>
							<div class="col-sm-7">
								<span class="product-name">Product Name</span>
								<span class="product-description">A long paragraph describing the product. its volume, type, etc with any additional things.</span>
							</div>
							<div class="col-sm-2"  style="text-align: center; padding-top: 20px;">
								Qty:
								<div class="cart_quantity_button">
									<a class="cart_quantity_up" href=""> + </a>
									<input class="cart_quantity_input" type="text" name="quantity" value="1" autocomplete="off" size="2">
									<a class="cart_quantity_down" href=""> - </a>
								</div>
								<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
							</div>
						</div>
						<div class="product-wrapper">
							<div class="col-sm-3" style="text-align: center;">
								<img src="../airsupply/static/airsupply/images/placeholder.png" class="img-responsive product-img">
								<span class="product-id"><b>Product ID:</b> 123456</span>
							</div>
							<div class="col-sm-7">
								<span class="product-name">Product Name</span>
								<span class="product-description">A long paragraph describing the product. its volume, type, etc with any additional things.</span>
							</div>
							<div class="col-sm-2"  style="text-align: center; padding-top: 20px;">
								Qty:
								<div class="cart_quantity_button">
									<a class="cart_quantity_up" href=""> + </a>
									<input class="cart_quantity_input" type="text" name="quantity" value="1" autocomplete="off" size="2">
									<a class="cart_quantity_down" href=""> - </a>
								</div>
								<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
							</div>
						</div>
						<div class="product-wrapper">
							<div class="col-sm-3" style="text-align: center;">
								<img src="../airsupply/static/airsupply/images/placeholder.png" class="img-responsive product-img">
								<span class="product-id"><b>Product ID:</b> 123456</span>
							</div>
							<div class="col-sm-7">
								<span class="product-name">Product Name</span>
								<span class="product-description">A long paragraph describing the product. its volume, type, etc with any additional things.</span>
							</div>
							<div class="col-sm-2"  style="text-align: center; padding-top: 20px;">
								Qty:
								<div class="cart_quantity_button">
									<a class="cart_quantity_up" href=""> + </a>
									<input class="cart_quantity_input" type="text" name="quantity" value="1" autocomplete="off" size="2">
									<a class="cart_quantity_down" href=""> - </a>
								</div>
								<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
							</div>
						</div>
						<div class="product-wrapper">
							<div class="col-sm-3" style="text-align: center;">
								<img src="../airsupply/static/airsupply/images/placeholder.png" class="img-responsive product-img">
								<span class="product-id"><b>Product ID:</b> 123456</span>
							</div>
							<div class="col-sm-7">
								<span class="product-name">Product Name</span>
								<span class="product-description">A long paragraph describing the product. its volume, type, etc with any additional things.</span>
							</div>
							<div class="col-sm-2"  style="text-align: center; padding-top: 20px;">
								Qty:
								<div class="cart_quantity_button">
									<a class="cart_quantity_up" href=""> + </a>
									<input class="cart_quantity_input" type="text" name="quantity" value="1" autocomplete="off" size="2">
									<a class="cart_quantity_down" href=""> - </a>
								</div>
								<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
							</div>
						</div>
						
					</div><!--features_items-->
				</div>
			</div>
		</div>
	</section>
	

    <script src="../airsupply/static/airsupply/js/jquery.js"></script>
	<script src="../airsupply/static/airsupply/js/bootstrap.min.js"></script>
	<script src="../airsupply/static/airsupply/js/jquery.scrollUp.min.js"></script>
	<script src="../airsupply/static/airsupply/js/price-range.js"></script>
    <script src="../airsupply/static/airsupply/js/jquery.prettyPhoto.js"></script>
    <script src="../airsupply/static/airsupply/js/main.js"></script>
</body>
</html>

templates/login.html
{% extends 'base1.html' %}
{% block title %}
Login
{% endblock %}

{% block body %}
	<section id="login-form"><!--form-->
		<div class="container">
			<div class="row">
				<div class="col-sm-6 col-sm-offset-3">
					<div class="login-form"><!-- register-user change classname to regiter-form in css too -->
						<h2>User Login</h2>
                        {% if error_message %}
                            <p class="error-msg">{{ error_message }}</p>
                        {% endif %}
						<form action="" id="login" method="post"> <!-- implement the form action -->
                            {% csrf_token %}
							<input type="text" name='username' placeholder="Username" />
							<input type="password" name='password' placeholder="Password"/>
							<button type="submit" class="btn btn-default">Login</button>
                            <span class="psw"><a href="{% url 'airsupply:forgot_password' %}"> Forgot password?</a></span>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section><!--/form-->
{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block body %}
	<section id="register-form"><!--form-->
		<div class="container">
			<div class="row">
				<div class="col-sm-6 col-sm-offset-3">
					<div class="signup-form"><!-- register-user change classname to regiter-form in css too -->
						<h2>New User Registration</h2>
						<form action="{% url 'airsupply:confirm_registration' %}" id="register" method="post">
                            {% csrf_token %}
							<label>Role:</label> <label>{{ role }}</label><br>
                            <label>Email:</label> <label>{{ email }}</label>

                            {{ form.as_p }}
                            <br>
							<button type="submit" class="btn btn-default">Register</button>
						</form>
					</div> <!-- /register-user -->

				</div>



			</div>
		</div>
	</section><!--/form-->

{% endblock %}